name: wnw11

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache tools
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            AutoItPortable_CI.zip
            C:\Program Files (x86)\AutoItPortable_CI
          key: v2
      - name: Download tools
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -sSfLO https://www.autoitscript.com/autoit3/mvps/mLipok/AutoItPortable_CI.zip
          Expand-Archive AutoItPortable_CI.zip "${env:ProgramFiles(x86)}"
      - name: Install tools
        run: |
      - name: Compile
        run: |
          Start-Process "${env:ProgramFiles(x86)}\AutoItPortable_CI\AutoIt3.exe" "`"${env:ProgramFiles(x86)}\AutoItPortable_CI\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3`" /NoStatus /prod /in WhyNotWin11.au3" -NoNewWindow -Wait
          sha256sum -b WhyNotWin*.exe > checksums.sha256
      - uses: actions/upload-artifact@v2
        with:
          name: WNW11
          path: |
            WhyNotWin11*.exe
            checksums.sha256
          if-no-files-found: error
      - name: Zip package
        if: startsWith(github.ref, 'refs/tags/')
        run: 7z a WhyNotWin11.zip WhyNotWin11*.exe checksums.sha256
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            WhyNotWin11*.exe
            WhyNotWin11.zip
            checksums.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
